### PR TITLE
fix: copy/paste firefox

### LINKED ISSUE #313: Bug: can't paste address Firefox
User can't change destination address in Firefox because the paste functionality is not working

### PR DESCRIPTION
**Pull request by ErinHales**
Closes #313 

 - Fixes copy/paste functionality for firefox (or where navigator clipboard API is not supported)
 - Fixes time estimation typo from 30-65 minutes to 35-60 minutes
 - Hides ugly number input increment button

### CODE REVIEW

File: src/utils/index.ts [hunk 1]
```diff
@@ -99,6 +105,53 @@ export function minutesTilConfirmation(timestamp: BigNumber): number {
...
+}
+
+export function copyTextToClipboard(text: string): boolean {
+  if (navigator.clipboard) {
+    navigator.clipboard.writeText(text).then(function() {
+      console.log('Async: Copying to clipboard was successful!')
+      return true
+    }, function(err) {
+      console.error('Async: Could not copy text: ', err)
+      return false
```
Comment (Imti) [inline src/utils/index.ts:141]: Should we return the fallback here as well?

Comment (ErinHales) [reply src/utils/index.ts:141]: Yeah that makes sense

**Review by Imti — APPROVED** [review]
🦊
